### ISSUE TITLE
[Question] your usage of tmpfs 

### ISSUE THREAD

**Issue by zilexa** [guillaumedsde/jackett-distroless#1]
I just noticed your docker examples because I was searching for `tmpfs`, trying to figure out if it would be useful for Jackett (and Sonarr, Bazarr etc) to make sure they use the RAM (32GB, only ~9 in use) as much as possible and limit SSD activity. 

I was going to add 
```
    tmpfs:
      - "/tmp"
```
To my compose, but now I see you even mount `/var` in there! 
Is that safe? What happens if you ever restart the container (or docker, or the host system)? I rarely do that, but if I do, I don't want Jackett to break.

**Comment by guillaumedsde** [comment]
Hi, if you use my docker image, I have set the `XDG_CONFIG_HOME=/config` environment variable, so Jackett will store its configuration there.

mounting a tmpfs in `var` is  a requirement of the s6-overlay for a read-only filesystem but Jackett shouldn't store anything important (probably even at all) in there so it should be safe.

I'm not sure if tmpfs tricks can speed up Jackett though, it probably already stores everything in RAM

**Comment by guillaumedsde** [comment]
I'll close this issue but don't hesitate if you have any more questions
